_target_: dataset.trance.TRANCEDataModule
name: trance_event

data_root: '/data/trance'
values_json: '/data/trance/resource/values.json'
properties_json: '/data/trance/resource/properties.json'

img_aug: true
move_out_aug: true

use_box: false
box_type: gt

batch_size: 128
num_workers: 16
pin_memory: true