_target_: model.Detector
height: 120
width: 160
rnn: GRU
teacher_forcing: true
c_pair_embed: 8
max_step: 4
c_hidden: [128]
arch: 'resnet18'
mode: 'subtract'
roi_type: 'pool'
roi_output_size: [2, 2]
roi_sample_ratio: -1
fc_img_en: [128]
fc_fusion: [128]